name: ğŸ’š CI for tests and linter to server

on: push

jobs:
  linter_job:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“‚ Checkout code
        uses: actions/checkout@v2

      - name: ğŸ› ï¸ Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: â¬ Install dependencies
        run: |
             npm install
             npm install -g ruff

      - name: ğŸ’„ Run Ruff
        run: |
          ruff check --output-format=github .
          ruff format --check .

  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“‚ Checkout code
        uses: actions/checkout@v2

      - name: ğŸ› ï¸ Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: â¬ Install dependencies
        run: npm install

      - name: âœ… Test
        run: npm test