name: ğŸ’š Tests and linter to server

on: push

jobs:
  linter_job:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“‚ Checkout code
        uses: actions/checkout@v2

      - name: ğŸ› ï¸ Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: â¬ Install dependencies
        run: npm install

      - name: ğŸš¨ Linter
        run: npm run lint

  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“‚ Checkout code
        uses: actions/checkout@v2

      - name: ğŸ› ï¸ Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: â¬ Install dependencies
        run: npm install

      - name: âœ… Test
        run: npm test:e2e